import math
import httpx
from typing import List, Optional
from sqlalchemy.orm import Session
from app.services.query_service import QueryService
from app.schemas.nearby_hospitals import *
from app.services.sarvam_service import text_to_speech, translate_text

class NearbyHospitalsService:

    def _haversine(self, lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        R = 6371
        dlat = math.radians(lat2 - lat1)
        dlon = math.radians(lon2 - lon1)
        a = (
            math.sin(dlat / 2) ** 2
            + math.cos(math.radians(lat1))
            * math.cos(math.radians(lat2))
            * math.sin(dlon / 2) ** 2
        )
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
        return R * c

    def _format_distance(self, km: float) -> str:
        if km < 1:
            return f"{int(km * 1000)} m"
        return f"{km:.1f} km"

    def _format_time(self, minutes: float) -> str:
        if minutes < 1:
            return "< 1 min"
        if minutes < 60:
            return f"{int(minutes)} min"
        hours = int(minutes // 60)
        mins = int(minutes % 60)
        return f"{hours}h {mins}m"

    def _estimate_drive_time(self, distance_km: float) -> float:
        if distance_km < 2:
            return (distance_km / 15) * 60
        elif distance_km < 5:
            return (distance_km / 20) * 60
        elif distance_km < 15:
            return (distance_km / 25) * 60
        else:
            return (distance_km / 35) * 60

    def find_nearest_hospitals(
        self, db: Session, lat: float, lng: float,
        radius_km: float = 5.0, max_results: int = 10,
        hospital_type: Optional[str] = None,
    ) -> List[NearbyHospital]:
        qs = QueryService(db)
        
        sql = """
            SELECT 
                l.hospital_name as name,
                l.type as hospital_type,
                l.latitude,
                l.longitude,
                COALESCE(h.hospital_id, 0) as id,
                h.rating
            FROM hospital_locations l
            LEFT JOIN hospitals h ON l.hospital_name = h.hospital_name AND l.city = h.city
            WHERE l.latitude IS NOT NULL AND l.longitude IS NOT NULL
              AND l.latitude != 0 AND l.longitude != 0
        """
        params = {}
        if hospital_type and hospital_type != "All Types":
            sql += " AND l.type = :type"
            params["type"] = hospital_type
            
        db_hospitals = qs.fetch_all(sql, params)
        
        nearby = []
        for h in db_hospitals:
            h_lat = float(h["latitude"])
            h_lng = float(h["longitude"])
            dist = self._haversine(lat, lng, h_lat, h_lng)

            if dist <= radius_km:
                drive_time = self._estimate_drive_time(dist)
                # handle non-integer hospital ids generated by dataset safely
                h_id = h["id"]
                if isinstance(h_id, str) and h_id.isdigit():
                    h_id = int(h_id)
                elif isinstance(h_id, str):
                    h_id = abs(hash(h_id)) % 1000000
                    
                nearby.append(NearbyHospital(
                    id=h_id,
                    name=h["name"],
                    hospital_type=h["hospital_type"] or 'Unknown',
                    latitude=h_lat,
                    longitude=h_lng,
                    address=None,
                    contact=None,
                    rating=float(h["rating"]) if h.get("rating") else None,
                    distance_km=round(dist, 2),
                    distance_display=self._format_distance(dist),
                    estimated_time_min=int(drive_time),
                    estimated_time_display=self._format_time(drive_time),
                ))

        nearby.sort(key=lambda x: x.distance_km)
        return nearby[:max_results]

    async def get_route(
        self, user_lat: float, user_lng: float,
        hospital_lat: float, hospital_lng: float,
    ) -> Optional[RouteDetails]:
        url = (
            f"https://router.project-osrm.org/route/v1/driving/"
            f"{user_lng},{user_lat};{hospital_lng},{hospital_lat}"
            f"?overview=full&geometries=geojson&steps=true"
        )
        async with httpx.AsyncClient(timeout=15.0) as client:
            try:
                response = await client.get(url)
                if response.status_code != 200:
                    return None

                data = response.json()
                if data.get("code") != "Ok" or not data.get("routes"):
                    return None

                route = data["routes"][0]
                legs = route["legs"][0]

                total_dist_km = route["distance"] / 1000
                total_dur_min = route["duration"] / 60
                
                coordinates = route["geometry"]["coordinates"]
                route_coords = [[coord[1], coord[0]] for coord in coordinates]

                steps = []
                for step in legs.get("steps", []):
                    instruction = step.get("maneuver", {}).get("type", "continue")
                    modifier = step.get("maneuver", {}).get("modifier", "")
                    road_name = step.get("name", "unnamed road")

                    if instruction == "depart": readable = f"Head towards {road_name}"
                    elif instruction == "arrive": readable = f"Arrive at destination"
                    elif instruction == "turn": readable = f"Turn {modifier} onto {road_name}"
                    elif instruction == "roundabout": readable = f"Take roundabout, exit to {road_name}"
                    elif instruction == "merge": readable = f"Merge onto {road_name}"
                    elif instruction == "fork": readable = f"Take the {modifier} fork onto {road_name}"
                    else: readable = f"Continue on {road_name}"

                    steps.append(RouteStep(
                        instruction=readable,
                        distance_m=step.get("distance", 0),
                        duration_s=step.get("duration", 0),
                        name=road_name,
                    ))

                google_url = f"https://www.google.com/maps/dir/{user_lat},{user_lng}/{hospital_lat},{hospital_lng}/@{user_lat},{user_lng},13z/data=!4m2!4m1!3e0"
                apple_url = f"https://maps.apple.com/?saddr={user_lat},{user_lng}&daddr={hospital_lat},{hospital_lng}&dirflg=d"

                return RouteDetails(
                    total_distance_km=round(total_dist_km, 1),
                    total_distance_display=self._format_distance(total_dist_km),
                    total_duration_min=round(total_dur_min, 1),
                    total_duration_display=self._format_time(total_dur_min),
                    route_geometry=route_coords,
                    steps=steps,
                    google_maps_url=google_url,
                    apple_maps_url=apple_url,
                )
            except Exception as e:
                print(f"OSRM routing error: {e}")
                return None

    def _build_nearest_voice_text(self, hospitals: List[NearbyHospital]) -> str:
        if not hospitals:
            return "No hospitals found nearby. Try increasing the search radius."

        h = hospitals[0]
        text = (
            f"The nearest hospital is {h.name}. "
            f"It is a {h.hospital_type} hospital, "
            f"{h.distance_display} away from your current location. "
            f"Estimated travel time is {h.estimated_time_display}."
        )

        if len(hospitals) >= 2:
            h2 = hospitals[1]
            text += f" The second nearest is {h2.name}, {h2.distance_display} away, approximately {h2.estimated_time_display}."

        if len(hospitals) >= 3:
            text += f" There are {len(hospitals)} hospitals within the search area."

        return text

    def _build_directions_voice_text(self, hospital: NearbyHospital, route: RouteDetails) -> str:
        text = f"Directions to {hospital.name}. Total distance is {route.total_distance_display}. Estimated time is {route.total_duration_display}. "
        important_steps = [s for s in route.steps if s.distance_m > 50][:3]
        for step in important_steps:
            text += f"{step.instruction}. "
        return text

    async def find_nearest_with_voice(self, db: Session, request: NearestHospitalsRequest) -> NearestHospitalsResponse:
        hospitals = self.find_nearest_hospitals(
            db, request.latitude, request.longitude,
            request.radius_km, request.max_results, request.hospital_type,
        )

        english_text = self._build_nearest_voice_text(hospitals)
        localized = english_text

        if request.language != "en-IN":
            try:
                translated = await translate_text(english_text, "en-IN", request.language)
                if translated: localized = translated
            except Exception: pass

        voice = None
        try:
            tts_base64 = await text_to_speech(localized, request.language, request.speaker)
            if tts_base64: voice = {"audio_base64": tts_base64, "format": "wav", "language": request.language}
        except Exception: pass

        return NearestHospitalsResponse(
            success=True,
            user_location=UserLocation(latitude=request.latitude, longitude=request.longitude),
            hospitals=hospitals,
            total_found=len(hospitals),
            radius_km=request.radius_km,
            voice_response=voice,
            text_response=localized,
        )

    async def get_directions_with_voice(
        self, db: Session, user_lat: float, user_lng: float, hospital_id: int, hospital_name: str, language: str = "en-IN", speaker: str = "anushka",
    ) -> DirectionsResponse:
        qs = QueryService(db)
        
        sql = """
            SELECT 
                l.hospital_name as name,
                l.type as hospital_type,
                l.latitude,
                l.longitude,
                COALESCE(h.hospital_id, 0) as id,
                h.rating
            FROM hospital_locations l
            LEFT JOIN hospitals h ON l.hospital_name = h.hospital_name AND l.city = h.city
            WHERE l.hospital_name = :name
            LIMIT 1
        """
        db_hospital = qs.fetch_one(sql, {"name": hospital_name})
        
        if not db_hospital or not db_hospital["latitude"] or not db_hospital["longitude"]:
            return DirectionsResponse(
                success=False,
                hospital=NearbyHospital(
                    id=0, name="Unknown", hospital_type="Unknown", latitude=0, longitude=0, distance_km=0, distance_display="N/A", estimated_time_min=0, estimated_time_display="N/A",
                ),
                route=RouteDetails(
                    total_distance_km=0, total_distance_display="N/A", total_duration_min=0, total_duration_display="N/A", route_geometry=[], steps=[], google_maps_url="", apple_maps_url="",
                ),
                text_response="Hospital not found.",
            )

        h_lat = float(db_hospital["latitude"])
        h_lng = float(db_hospital["longitude"])
        dist = self._haversine(user_lat, user_lng, h_lat, h_lng)
        drive_time = self._estimate_drive_time(dist)

        nearby_h = NearbyHospital(
            id=hospital_id,
            name=db_hospital["name"],
            hospital_type=db_hospital["hospital_type"] or 'Unknown',
            latitude=h_lat,
            longitude=h_lng,
            rating=float(db_hospital["rating"]) if db_hospital.get("rating") else None,
            distance_km=round(dist, 2),
            distance_display=self._format_distance(dist),
            estimated_time_min=int(drive_time),
            estimated_time_display=self._format_time(drive_time),
        )

        route = await self.get_route(user_lat, user_lng, h_lat, h_lng)

        if not route:
            google_url = f"https://www.google.com/maps/dir/{user_lat},{user_lng}/{h_lat},{h_lng}"
            apple_url = f"https://maps.apple.com/?saddr={user_lat},{user_lng}&daddr={h_lat},{h_lng}&dirflg=d"
            route = RouteDetails(
                total_distance_km=round(dist, 1), total_distance_display=self._format_distance(dist),
                total_duration_min=round(drive_time, 1), total_duration_display=self._format_time(drive_time),
                route_geometry=[[user_lat, user_lng], [h_lat, h_lng]],
                steps=[RouteStep(instruction=f"Head towards {nearby_h.name}", distance_m=dist*1000, duration_s=drive_time*60, name="Direct route")],
                google_maps_url=google_url, apple_maps_url=apple_url,
            )

        english_text = self._build_directions_voice_text(nearby_h, route)
        localized = english_text

        if language != "en-IN":
            try:
                translated = await translate_text(english_text, "en-IN", language)
                if translated: localized = translated
            except Exception: pass

        voice = None
        try:
            tts_base64 = await text_to_speech(localized, language, speaker)
            if tts_base64: voice = {"audio_base64": tts_base64, "format": "wav", "language": language}
        except Exception: pass

        return DirectionsResponse(
            success=True, hospital=nearby_h, route=route, voice_response=voice, text_response=localized,
        )


nearby_hospitals_service = NearbyHospitalsService()
